### PR TITLE
Get relative click coordinates on click (js)

### PR DESCRIPTION
**Pull request by ergl**
See [demo](http://codepen.io/Roboe/pen/qdLPOx) (props to @Roboe)

EDIT: Also, this was a quick thing, so any suggestions and improvements are welcome

### CODE REVIEW

**Comment by Roboe** [comment]
(Again, not IE10< support. Damn it, Microsoft...)

There was a bug in my Codepen approach. If you scroll on the page, the coordinates are not valid.
I suppose there's a property somewhere that tells you the scroll distance from page top and left, but I didn't look into it.

P.D.: Destructuring is coming in ES2015, :D

**Comment by ergl** [comment]
Sure, I'll push a change for that

**Comment by ergl** [comment]
I should probably merge these two commits together before merging - but I'll wait until this code seems good to merge to do that

**Comment by Roboe** [comment]
Babel does [a very similar thing](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=[x%2C%20y]%20%3D%20getRelativeCoordinates%28event%29).

Great job!

**Comment by ergl** [comment]
This seems good to merge now, I went ahead and squashed everything together

**Pull request merged**
